### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method restartApp on channel flutter_restart)

### ISSUE THREAD

**Issue by Rahuldavaskar** [justgam3/FlutterRestartPlugin#1]
Unhandled Exception: MissingPluginException(No implementation found for method restartApp on channel flutter_restart)

**Comment by Rahuldavaskar** [comment]
after implementing this plugin i am getting this issue

**Comment by kateile** [comment]
same here

**Comment by zaif-bsol** [comment]
Did you tried to Stop the app and restart? Not talking about, Hot Restart, do an actual Restart of app

**Comment by Fried-man** [comment]
same issue. I have reset the phone simulator, run flutter clean and flutter pub get, invalidated caches and restarted. Nothing has worked. All I get is this:
`[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method restartApp on channel restart)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      Restart.restartApp (package:restart_app/restart_app.dart:11:8)
<asynchronous suspension>`

**Comment by forgecodex** [comment]
do an actual Restart of app ，Now Working！ Thankyou

**Comment by kaning** [comment]
Same issue here... I have killed the app, uninstalled the app, done `flutter clean`, rerun the app from cold and I still get `No implementation found for method restartApp on channel restart`

**Comment by toshan121** [comment]
Rebuilt and reinstalled. It worked.

**Comment by stephanie-finch** [comment]
getting this issue as well, even after flutter clean & rebuilding the app.

**Comment by unshami** [comment]
same issue tried 
- invalidate and restart android stuido
- flutter clean and rebuilding the app
- delete the app from simulator
- flutter upgraded to  3.7.8 
Still same error
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method restartApp on channel restart)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)
<asynchronous suspension>
#1      Restart.restartApp (package:restart_app/restart_app.dart:11:8)
<asynchronous suspension>

**Comment by mkbsugita** [comment]
Unhandled Exception: MissingPluginException(No implementation found for method restartApp on channel restart)

**Comment by mkbsugita** [comment]
I did `ios/Runner/Info.plist` but...

```
+    <key>CFBundleURLName</key>
+      <!-- You can find it on /ios/project.pbxproj - 'PRODUCT_BUNDLE_IDENTIFIER' -->
+    <string>jp.ne.campanyname.appname</string>
+    <key>CFBundleURLSchemes</key>
+    <array>
+      <!-- Your app title -->
+      <string>App name</string>
+    </array>
+

```
